import type { FieldDef } from "../../../types";
import { codeNameFields } from "./shared";

const text = (name: string, label: string, required = false): FieldDef => ({
  name,
  label,
  type: "text",
  required,
  maxLength: 255,
});

export const systemFormFields = {
  language: codeNameFields(),
  label_source: codeNameFields(),
  vat_kind: codeNameFields(),
  map_accountant: codeNameFields(),
  profit_loss_section: codeNameFields(),
  document: codeNameFields(),

  vat_rate_code: [
    ...codeNameFields(),
    { name: "rate", label: "Rate", type: "number", required: true },
  ] satisfies FieldDef[],

  cash_flow_section: [
    ...codeNameFields(),
    { name: "polarity", label: "Polarity", type: "number" },
  ] satisfies FieldDef[],

  venue: [
    ...codeNameFields(),
    {
      name: "order_type",
      label: "Order type",
      type: "select",
      options: [
        { value: "0", label: "Trade show" },
        { value: "1", label: "On road" },
        { value: "2", label: "Web" },
      ],
    },
  ] satisfies FieldDef[],

  shipping_charge: [
    ...codeNameFields(),
    { name: "amount_needed", label: "Amount needed", type: "boolean" },
  ] satisfies FieldDef[],

  area: [
    ...codeNameFields(),
    text("iso_code", "ISO code"),
    { name: "uk_for_hmrc", label: "UK for HMRC", type: "boolean" },
  ] satisfies FieldDef[],

  warehouse: [
    { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
    { name: "code", label: "Code", type: "text", required: true, maxLength: 40 },
    text("address_line1", "Address line 1"),
    text("address_line2", "Address line 2"),
    text("region", "Region"),
    text("town", "Town"),
    text("state", "State"),
    text("zip", "Zip"),
    text("contact", "Contact"),
    text("phone", "Phone"),
    text("fax", "Fax"),
    text("email", "Email"),
    {
      name: "country_id",
      label: "Country",
      type: "reference",
      referenceKlass: "Country",
      placeholder: "Search countries…",
    },
    { name: "master", label: "Master", type: "boolean" },
  ] satisfies FieldDef[],

  profit_centre: [
    ...codeNameFields(),
    text("address_1", "Address 1"),
    text("address_2", "Address 2"),
    text("region", "Region"),
    text("town", "Town"),
    text("state", "State"),
    text("zip_code", "Zip code"),
    text("vat", "VAT"),
    text("phone_main", "Phone main"),
    text("phone_sales", "Phone sales"),
    text("phone_accts", "Phone accounts"),
    text("fax", "Fax"),
    text("email", "Email"),
    text("website", "Website"),
    { name: "next_proforma", label: "Next proforma", type: "number" },
    { name: "next_invoice", label: "Next invoice", type: "number" },
    { name: "next_credit", label: "Next credit", type: "number" },
    { name: "next_cust_ord", label: "Next customer order", type: "number" },
    { name: "next_supp_ord", label: "Next supplier order", type: "number" },
    { name: "next_subship", label: "Next subship", type: "number" },
    {
      name: "country_id",
      label: "Country",
      type: "reference",
      referenceKlass: "Country",
      placeholder: "Search countries…",
    },
  ] satisfies FieldDef[],

  bank_account: [
    { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
    { name: "code", label: "Code", type: "text", required: true, maxLength: 40 },
    text("sort_code", "Sort code"),
    text("account_number", "Account number"),
    text("swift", "SWIFT"),
    text("iban", "IBAN"),
    text("cust_direct_control", "Customer direct control"),
    text("supp_acc_control", "Supplier account control"),
    text("supp_direct_control", "Supplier direct control"),
    { name: "current_balance", label: "Current balance", type: "number" },
    { name: "current_balance_gbp", label: "Current balance (GBP)", type: "number" },
    { name: "opening_balance", label: "Opening balance", type: "number" },
    { name: "opening_balance_gbp", label: "Opening balance (GBP)", type: "number" },
    {
      name: "currency_id",
      label: "Currency",
      type: "reference",
      referenceKlass: "Currency",
      placeholder: "Search currencies…",
    },
  ] satisfies FieldDef[],

  cost_code: [
    { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
    { name: "code", label: "Code", type: "text", required: true, maxLength: 40 },
    text("category", "Category"),
    {
      name: "kind",
      label: "Kind",
      type: "select",
      options: [
        { value: "income", label: "Income" },
        { value: "expenditure", label: "Expenditure" },
      ],
    },
    text("report", "Report"),
    {
      name: "vat_box",
      label: "VAT box",
      type: "text",
      maxLength: 40,
    },
    {
      name: "map_accountant_id",
      label: "Map accountant",
      type: "reference",
      referenceKlass: "MapAccountant",
      placeholder: "Search accountants…",
    },
    {
      name: "cash_flow_section_id",
      label: "Cash flow section",
      type: "reference",
      referenceKlass: "CashFlowSection",
      placeholder: "Search cash flow sections…",
    },
    {
      name: "profit_loss_section_id",
      label: "Profit & loss section",
      type: "reference",
      referenceKlass: "ProfitLossSection",
      placeholder: "Search P&L sections…",
    },
    { name: "vat_intra_stat", label: "VAT intra stat", type: "boolean" },
  ] satisfies FieldDef[],

  order_kind: [
    { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
    { name: "code", label: "Code", type: "text", required: true, maxLength: 40 },
    { name: "flags_avail_calc", label: "Availability calc", type: "boolean", readPath: "flags.avail_calc" },
    { name: "flags_spare_calc", label: "Spare calc", type: "boolean", readPath: "flags.spare_calc" },
    {
      name: "flags_likely_confirmed",
      label: "Likely confirmed",
      type: "boolean",
      readPath: "flags.likely_confirmed",
    },
    {
      name: "flags_allow_allocation",
      label: "Allow allocation",
      type: "boolean",
      readPath: "flags.allow_allocation",
    },
  ] satisfies FieldDef[],

  invoice_environment: [
    { name: "name", label: "Name", type: "text", required: true, maxLength: 120 },
    { name: "code", label: "Code", type: "text", required: true, maxLength: 40 },
    { name: "title", label: "Title", type: "text", required: true, maxLength: 120 },
    {
      name: "price_category_id",
      label: "Price category",
      type: "reference",
      referenceKlass: "Stock::PriceCategory",
      placeholder: "Search price categories…",
    },
    {
      name: "currency_id",
      label: "Currency",
      type: "reference",
      referenceKlass: "Currency",
      placeholder: "Search currencies…",
    },
    {
      name: "bank_account_id",
      label: "Bank account",
      type: "reference",
      referenceKlass: "BankAccount",
      placeholder: "Search bank accounts…",
    },
    {
      name: "vat_kind_id",
      label: "VAT kind",
      type: "reference",
      referenceKlass: "VatKind",
      placeholder: "Search VAT kinds…",
    },
    {
      name: "vat_rate_code_id",
      label: "VAT rate code",
      type: "reference",
      referenceKlass: "VatRateCode",
      placeholder: "Search VAT rate codes…",
    },
    {
      name: "main_code_id",
      label: "Main code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    {
      name: "post_code_id",
      label: "Post code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    {
      name: "control_code_id",
      label: "Control code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    {
      name: "buy_code_id",
      label: "Buy code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    {
      name: "discount_taken_code_id",
      label: "Discount taken code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    {
      name: "discount_given_code_id",
      label: "Discount given code",
      type: "reference",
      referenceKlass: "CostCode",
      placeholder: "Search cost codes…",
    },
    { name: "vat_reg_needed", label: "VAT reg needed", type: "boolean" },
    { name: "finances", label: "Finances", type: "boolean" },
    { name: "stock", label: "Stock", type: "boolean" },
    { name: "shop", label: "Shop", type: "boolean" },
  ] satisfies FieldDef[],
} as const;
