/**
 * Logical keys for reference pickers. Values match `REFERENCE_SOURCES` in
 * `reference-sources.ts` (backed by platform list APIs, not `/autocompletes`).
 */
export const ReferenceKlass = {
  Category: "StockSettings::Category",
  CategoryGroup: "StockSettings::CategoryGroup",
  Colour: "StockSettings::Colour",
  ColourOption: "StockSettings::ColourOption",
  Display: "StockSettings::Display",
  Assortment: "StockSettings::Assortment",
  Collection: "StockSettings::Collection",
  Selection: "StockSettings::Selection",
  TargetGender: "StockSettings::TargetGender",
  Unit: "StockSettings::Unit",
  Packaging: "StockSettings::Packaging",
  CustomTarrifCode: "StockSettings::CustomTariffCode",
  VatRateCode: "VatRateCode",
  StockBuyer: "StockBuyer",
  Supplier: "Supplier",
  Manufacturer: "Supplier",
  FittingSizePackAssortment: "StockSettings::FittingSizePackAssortment",
  FittingSizeMeasure: "StockSettings::FittingSizeMeasure",
  FittingSizeSpec: "StockSettings::FittingSizeSpec",
  DimensionPackAssortment: "StockSettings::DimensionPackAssortment",
  DimensionMeasure: "StockSettings::DimensionMeasure",
  DimensionSpec: "StockSettings::DimensionSpec",
  RingSize: "StockSettings::RingSize",
  Material: "StockSettings::Material",
  Range: "StockSettings::Range",
  AmazonTemplate: "StockSettings::AmazonTemplate",
  AmazonProductType: "StockSettings::AmazonProductType",
  AmazonUsItemType: "StockSettings::AmazonUsItemType",
  AmazonMaterial: "StockSettings::AmazonMaterial",
  AmazonMetalType: "StockSettings::AmazonMetalType",
  AmazonMetalStamp: "StockSettings::AmazonMetalStamp",
  Country: "Country",
  AddressCategory: "AddressSettings::Category",
  Area: "Area",
  AccountManager: "AddressSettings::AccountManager",
  Agent: "AddressSettings::Agent",
  ProfitCentre: "ProfitCentre",
  InvoiceEnvironment: "InvoiceEnvironment",
  PriceCategory: "Stock::PriceCategory",
  CostCode: "CostCode",
  VatKind: "VatKind",
  OrderKind: "OrderKind",
  Language: "Language",
  LabelSource: "LabelSource",
  SpecialCustomer: "AddressSettings::SpecialCustomer",
  PayTerm: "AddressSettings::PayTerm",
  PaymentMethod: "AddressSettings::PaymentMethod",
  BankAccount: "BankAccount",
  ShipFrom: "AddressSettings::ShipFrom",
  Warehouse: "Warehouse",
  ShipMethod: "AddressSettings::ShipMethod",
  ShippingCharge: "ShippingCharge",
  Currency: "Currency",
  UpsService: "AddressSettings::UpsService",
  MessagePurpose: "MessageSettings::MessagePurpose",
  GeneralMessage: "MessageSettings::GeneralMessage",
  Document: "Document",
  MapAccountant: "MapAccountant",
  CashFlowSection: "CashFlowSection",
  ProfitLossSection: "ProfitLossSection",
  /** Another stock record used as packaging (see `stock_packaging_id`). */
  Stock: "Stock",
} as const;

export type ReferenceKlassName = (typeof ReferenceKlass)[keyof typeof ReferenceKlass];
