import {
  settingsAreas,
  settingsBankAccounts,
  settingsCashFlowSections,
  settingsCostCodes,
  settingsDocuments,
  settingsInvoiceEnvironments,
  settingsLabelSources,
  settingsLanguages,
  settingsMapAccountants,
  settingsOrderKinds,
  settingsProfitCentres,
  settingsProfitLossSections,
  settingsShippingCharges,
  settingsVatKinds,
  settingsVatRateCodes,
  settingsVenues,
  settingsWarehouses,
} from "@/api/settings/system";
import type { SettingsResource, SettingsSectionConfig } from "../types";
import {
  mapAreaPayload,
  mapBankAccountPayload,
  mapCashFlowSectionPayload,
  mapCodeNamePayload,
  mapCostCodePayload,
  mapInvoiceEnvironmentPayload,
  mapOrderKindPayload,
  mapProfitCentrePayload,
  mapShippingChargePayload,
  mapVatRateCodePayload,
  mapVenuePayload,
  mapWarehousePayload,
} from "../payload-maps";
import { mapOrderKindFromRow } from "../row-maps";
import { SettingsModuleFormData } from "./columns/formFields";
import { buildSettingListingColumns } from "./columns/listingData";
import { listing } from "./helpers";

export const systemSettingsSections: Partial<Record<string, SettingsSectionConfig>> = {
  "others/profit-centre": listing({
    resource: settingsProfitCentres as unknown as SettingsResource,
    singular: "Profit centre",
    plural: "Profit centres",
    bodyKey: "profit_centre",
    fields: SettingsModuleFormData.profit_centre,
    mapWritePayload: mapProfitCentrePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/area": listing({
    resource: settingsAreas as unknown as SettingsResource,
    singular: "Area",
    plural: "Areas",
    bodyKey: "area",
    fields: SettingsModuleFormData.area,
    mapWritePayload: mapAreaPayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/invoice-environment": listing({
    resource: settingsInvoiceEnvironments as unknown as SettingsResource,
    singular: "Invoice environment",
    plural: "Invoice environments",
    bodyKey: "invoice_environment",
    fields: SettingsModuleFormData.invoice_environment,
    mapWritePayload: mapInvoiceEnvironmentPayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/warehouse": listing({
    resource: settingsWarehouses as unknown as SettingsResource,
    singular: "Warehouse",
    plural: "Warehouses",
    bodyKey: "warehouse",
    fields: SettingsModuleFormData.warehouse,
    mapWritePayload: mapWarehousePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/shipping-charges": listing({
    resource: settingsShippingCharges as unknown as SettingsResource,
    singular: "Shipping charge",
    plural: "Shipping charges",
    bodyKey: "shipping_charge",
    fields: SettingsModuleFormData.shipping_charge,
    mapWritePayload: mapShippingChargePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/cost-codes": listing({
    resource: settingsCostCodes as unknown as SettingsResource,
    singular: "Cost code",
    plural: "Cost codes",
    bodyKey: "cost_code",
    fields: SettingsModuleFormData.cost_code,
    mapWritePayload: mapCostCodePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/order-kinds": listing({
    resource: settingsOrderKinds as unknown as SettingsResource,
    singular: "Order kind",
    plural: "Order kinds",
    bodyKey: "order_kind",
    fields: SettingsModuleFormData.order_kind,
    mapWritePayload: mapOrderKindPayload,
    mapFromRow: mapOrderKindFromRow,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/languages": listing({
    resource: settingsLanguages as unknown as SettingsResource,
    singular: "Language",
    plural: "Languages",
    bodyKey: "language",
    fields: SettingsModuleFormData.language,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/label-sources": listing({
    resource: settingsLabelSources as unknown as SettingsResource,
    singular: "Label source",
    plural: "Label sources",
    bodyKey: "label_source",
    fields: SettingsModuleFormData.label_source,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/var-kinds": listing({
    resource: settingsVatKinds as unknown as SettingsResource,
    singular: "VAT kind",
    plural: "VAT kinds",
    bodyKey: "vat_kind",
    fields: SettingsModuleFormData.vat_kind,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/vat-rate-codes": listing({
    resource: settingsVatRateCodes as unknown as SettingsResource,
    singular: "VAT rate code",
    plural: "VAT rate codes",
    bodyKey: "vat_rate_code",
    fields: SettingsModuleFormData.vat_rate_code,
    mapWritePayload: mapVatRateCodePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/bank-account": listing({
    resource: settingsBankAccounts as unknown as SettingsResource,
    singular: "Bank account",
    plural: "Bank accounts",
    bodyKey: "bank_account",
    fields: SettingsModuleFormData.bank_account,
    mapWritePayload: mapBankAccountPayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/map-accountants": listing({
    resource: settingsMapAccountants as unknown as SettingsResource,
    singular: "Map accountant",
    plural: "Map accountants",
    bodyKey: "map_accountant",
    fields: SettingsModuleFormData.map_accountant,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/profit-loss": listing({
    resource: settingsProfitLossSections as unknown as SettingsResource,
    singular: "Profit & loss section",
    plural: "Profit & loss sections",
    bodyKey: "profit_loss_section",
    fields: SettingsModuleFormData.profit_loss_section,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/cash-flow": listing({
    resource: settingsCashFlowSections as unknown as SettingsResource,
    singular: "Cash flow section",
    plural: "Cash flow sections",
    bodyKey: "cash_flow_section",
    fields: SettingsModuleFormData.cash_flow_section,
    mapWritePayload: mapCashFlowSectionPayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/venues": listing({
    resource: settingsVenues as unknown as SettingsResource,
    singular: "Venue",
    plural: "Venues",
    bodyKey: "venue",
    fields: SettingsModuleFormData.venue,
    mapWritePayload: mapVenuePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
  "others/documents": listing({
    resource: settingsDocuments as unknown as SettingsResource,
    singular: "Document",
    plural: "Documents",
    bodyKey: "document",
    fields: SettingsModuleFormData.document,
    mapWritePayload: mapCodeNamePayload,
    buildListingColumns: buildSettingListingColumns,
  }),
};
