import {
  stockAmazonBrowseNodes,
  stockAmazonMaterials,
  stockAmazonMetalStamps,
  stockAmazonMetalTypes,
  stockAmazonProductTypes,
  stockAmazonTemplates,
  stockAmazonUsItemTypes,
  stockAssortments,
  stockCardings,
  stockCategories,
  stockCategoryGroups,
  stockCollections,
  stockColourOptions,
  stockColours,
  stockCostsAssembly,
  stockCostsPacking,
  stockCustomTarrifCodes,
  stockDimensionMeasures,
  stockDimensionMessages,
  stockDimensionPackAssortments,
  stockDimensionSpecs,
  stockDisplays,
  stockFittingMessages,
  stockFittingSizeMeasures,
  stockFittingSizePackAssortments,
  stockFittingSizeSpecs,
  stockJoeOnlineRanges,
  stockMarketingBlurbs,
  stockMaterials,
  stockPackagings,
  stockRanges,
  stockRingSizes,
  stockSelections,
  stockTargetGenders,
  stockUnits,
  stockWebStockAvailabilityMessages,
} from "@/api/settings/stock";
import type { SettingsResource, SettingsResourceEntry } from "./types";
import {
  F_AMAZON_BROWSE_NODE,
  F_AMAZON_PRODUCT_TYPE,
  F_CATEGORY,
  F_CODE_NAME,
  F_CODE_NAME_VALUES,
  F_COST_ROW,
  F_DIMENSION_MESSAGE,
  F_FITTING_MESSAGE,
  F_FITTING_PACK_ASSORTMENT,
  F_MARKETING_BLURB,
  F_MATERIAL,
  F_NAME,
  F_RING_SIZE,
  F_WEB_STOCK_AVAILABILITY,
} from "./fields";
import {
  mapAmazonBrowseNodePayload,
  mapAmazonProductTypePayload,
  mapCategoryPayload,
  mapCodeNamePayload,
  mapCostAssemblyPayload,
  mapCostPackingPayload,
  mapDimensionMessagePayload,
  mapFittingMessagePayload,
  mapFittingPackAssortmentPayload,
  mapMarketingBlurbPayload,
  mapMaterialPayload,
  mapNameOnlyPayload,
  mapRingSizePayload,
  mapSpecWithValuesPayload,
  mapWebStockAvailabilityPayload,
} from "./payload-maps";

export const settingsResourceRegistry: Partial<Record<string, SettingsResourceEntry>> = {
  "stock/category/categories": {
    resource: stockCategories as unknown as SettingsResource,
    singular: "Category",
    plural: "Categories",
    bodyKey: "category",
    fields: F_CATEGORY,
    mapWritePayload: mapCategoryPayload,
  },
  "stock/category/groups": {
    resource: stockCategoryGroups as unknown as SettingsResource,
    singular: "Category group",
    plural: "Category groups",
    bodyKey: "category_group",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/category/packaging": {
    resource: stockPackagings as unknown as SettingsResource,
    singular: "Packaging",
    plural: "Packaging types",
    bodyKey: "packaging",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },

  "stock/fittings/sizes-pack-assortments": {
    resource: stockFittingSizePackAssortments as unknown as SettingsResource,
    singular: "Pack assortment",
    plural: "Pack assortments",
    bodyKey: "fitting_size_pack_assortment",
    fields: F_FITTING_PACK_ASSORTMENT,
    mapWritePayload: mapFittingPackAssortmentPayload,
  },
  "stock/fittings/sizes-specs": {
    resource: stockFittingSizeSpecs as unknown as SettingsResource,
    singular: "Fitting size spec",
    plural: "Fitting size specs",
    bodyKey: "fitting_size_spec",
    fields: F_CODE_NAME_VALUES,
    mapWritePayload: mapSpecWithValuesPayload,
  },
  "stock/fittings/sizes-measures": {
    resource: stockFittingSizeMeasures as unknown as SettingsResource,
    singular: "Fitting size measure",
    plural: "Fitting size measures",
    bodyKey: "fitting_size_measure",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/fittings/messages": {
    resource: stockFittingMessages as unknown as SettingsResource,
    singular: "Fitting message",
    plural: "Fitting messages",
    bodyKey: "fitting_message",
    fields: F_FITTING_MESSAGE,
    mapWritePayload: mapFittingMessagePayload,
  },

  "stock/dimensions/pack-assortments": {
    resource: stockDimensionPackAssortments as unknown as SettingsResource,
    singular: "Dimension pack assortment",
    plural: "Dimension pack assortments",
    bodyKey: "dimension_pack_assortment",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/dimensions/specs": {
    resource: stockDimensionSpecs as unknown as SettingsResource,
    singular: "Dimension spec",
    plural: "Dimension specs",
    bodyKey: "dimension_spec",
    fields: F_CODE_NAME_VALUES,
    mapWritePayload: mapSpecWithValuesPayload,
  },
  "stock/dimensions/measures": {
    resource: stockDimensionMeasures as unknown as SettingsResource,
    singular: "Dimension measure",
    plural: "Dimension measures",
    bodyKey: "dimension_measure",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/dimensions/messages": {
    resource: stockDimensionMessages as unknown as SettingsResource,
    singular: "Dimension message",
    plural: "Dimension messages",
    bodyKey: "dimension_message",
    fields: F_DIMENSION_MESSAGE,
    mapWritePayload: mapDimensionMessagePayload,
  },

  "stock/stock/selections": {
    resource: stockSelections as unknown as SettingsResource,
    singular: "Selection",
    plural: "Selections",
    bodyKey: "selection",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/stock/collections": {
    resource: stockCollections as unknown as SettingsResource,
    singular: "Collection",
    plural: "Collections",
    bodyKey: "collection",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/stock/stock-ranges": {
    resource: stockRanges as unknown as SettingsResource,
    singular: "Range",
    plural: "Ranges",
    bodyKey: "range",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/stock/marketing": {
    resource: stockMarketingBlurbs as unknown as SettingsResource,
    singular: "Marketing blurb",
    plural: "Marketing blurbs",
    bodyKey: "marketing_blurb",
    fields: F_MARKETING_BLURB,
    mapWritePayload: mapMarketingBlurbPayload,
  },

  "stock/amazon/templates": {
    resource: stockAmazonTemplates as unknown as SettingsResource,
    singular: "Amazon template",
    plural: "Amazon templates",
    bodyKey: "amazon_template",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/amazon/product-types": {
    resource: stockAmazonProductTypes as unknown as SettingsResource,
    singular: "Amazon product type",
    plural: "Amazon product types",
    bodyKey: "amazon_product_type",
    fields: F_AMAZON_PRODUCT_TYPE,
    mapWritePayload: mapAmazonProductTypePayload,
  },
  "stock/amazon/browse-nodes": {
    resource: stockAmazonBrowseNodes as unknown as SettingsResource,
    singular: "Amazon browse node",
    plural: "Amazon browse nodes",
    bodyKey: "amazon_browse_node",
    fields: F_AMAZON_BROWSE_NODE,
    mapWritePayload: mapAmazonBrowseNodePayload,
  },
  "stock/amazon/materials": {
    resource: stockAmazonMaterials as unknown as SettingsResource,
    singular: "Amazon material",
    plural: "Amazon materials",
    bodyKey: "amazon_material",
    fields: F_NAME,
    mapWritePayload: mapNameOnlyPayload,
  },
  "stock/amazon/metal-types": {
    resource: stockAmazonMetalTypes as unknown as SettingsResource,
    singular: "Amazon metal type",
    plural: "Amazon metal types",
    bodyKey: "amazon_metal_type",
    fields: F_NAME,
    mapWritePayload: mapNameOnlyPayload,
  },
  "stock/amazon/metal-stamps": {
    resource: stockAmazonMetalStamps as unknown as SettingsResource,
    singular: "Amazon metal stamp",
    plural: "Amazon metal stamps",
    bodyKey: "amazon_metal_stamp",
    fields: F_NAME,
    mapWritePayload: mapNameOnlyPayload,
  },
  "stock/amazon/us-item-types": {
    resource: stockAmazonUsItemTypes as unknown as SettingsResource,
    singular: "Amazon US item type",
    plural: "Amazon US item types",
    bodyKey: "amazon_us_item_type",
    fields: F_NAME,
    mapWritePayload: mapNameOnlyPayload,
  },

  "stock/colors": {
    resource: stockColours as unknown as SettingsResource,
    singular: "Colour",
    plural: "Colours",
    bodyKey: "colour",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/colors-options": {
    resource: stockColourOptions as unknown as SettingsResource,
    singular: "Colour option",
    plural: "Colour options",
    bodyKey: "colour_option",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/sizes": {
    resource: stockRingSizes as unknown as SettingsResource,
    singular: "Ring size",
    plural: "Ring sizes",
    bodyKey: "ring_size",
    fields: F_RING_SIZE,
    mapWritePayload: mapRingSizePayload,
  },
  "stock/sizes/web-availability": {
    resource: stockWebStockAvailabilityMessages as unknown as SettingsResource,
    singular: "Web availability message",
    plural: "Web availability messages",
    bodyKey: "web_stock_availability_message",
    fields: F_WEB_STOCK_AVAILABILITY,
    mapWritePayload: mapWebStockAvailabilityPayload,
  },
  "stock/units": {
    resource: stockUnits as unknown as SettingsResource,
    singular: "Unit",
    plural: "Units",
    bodyKey: "unit",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/carding": {
    resource: stockCardings as unknown as SettingsResource,
    singular: "Carding",
    plural: "Cardings",
    bodyKey: "carding",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/displays": {
    resource: stockDisplays as unknown as SettingsResource,
    singular: "Display",
    plural: "Displays",
    bodyKey: "display",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/assembly-costs": {
    resource: stockCostsAssembly as unknown as SettingsResource,
    singular: "Assembly cost",
    plural: "Assembly costs",
    bodyKey: "cost",
    fields: F_COST_ROW,
    mapWritePayload: mapCostAssemblyPayload,
  },
  "stock/packing-costs": {
    resource: stockCostsPacking as unknown as SettingsResource,
    singular: "Packing cost",
    plural: "Packing costs",
    bodyKey: "cost",
    fields: F_COST_ROW,
    mapWritePayload: mapCostPackingPayload,
  },

  "stock/other-assortments": {
    resource: stockAssortments as unknown as SettingsResource,
    singular: "Assortment",
    plural: "Assortments",
    bodyKey: "assortment",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/other-genders": {
    resource: stockTargetGenders as unknown as SettingsResource,
    singular: "Target gender",
    plural: "Target genders",
    bodyKey: "target_gender",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/other-materials": {
    resource: stockMaterials as unknown as SettingsResource,
    singular: "Material",
    plural: "Materials",
    bodyKey: "material",
    fields: F_MATERIAL,
    mapWritePayload: mapMaterialPayload,
  },
  "stock/other-online-ranges": {
    resource: stockJoeOnlineRanges as unknown as SettingsResource,
    singular: "Joe online range",
    plural: "Joe online ranges",
    bodyKey: "joe_online_range",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
  "stock/other-custom-tariff-codes": {
    resource: stockCustomTarrifCodes as unknown as SettingsResource,
    singular: "Custom tariff code",
    plural: "Custom tariff codes",
    bodyKey: "custom_tarrif_code",
    fields: F_CODE_NAME,
    mapWritePayload: mapCodeNamePayload,
  },
};

export function getSettingsResource(slug: string): SettingsResourceEntry | undefined {
  return settingsResourceRegistry[slug];
}
